{% set name = "cpp-tabulate" %}
{% set version = "1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/p-ranav/tabulate/archive/v{{ version }}.tar.gz
  sha256: c20cdc3175526a069e932136a7cbdf6f27b137bdb4fc5f574eb5a497228c8e11

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]

test:
  commands:
    - test -d ${PREFIX}/include/tabulate  # [unix]
    - test -f ${PREFIX}/include/tabulate/table.hpp  # [unix]
    - if exist %LIBRARY_PREFIX%\include\tabulate\table.hpp (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/p-ranav/tabulate
  license: MIT
  license_file: LICENSE
  summary: Tabulate is a header-only library for printing aligned, formatted, and colorized tables.

extra:
  recipe-maintainers:
    - p-ranav
    - SylvainCorlay
    - wolfv
    - marimeireles
